import sqlite3

def verify_user():
    """
    verify if user input correct username/password
    if True then run get_data funtion else programs ends
    """
    print("Student Exam Score Result")
    print("Please type in your username and password to access result")
    username = input("Username: ")
    password = input("Password: ")
    if username == "admin" and password == "2020":
        get_data()
    else:
        print("Your username or password is incorrect")

def get_data():
    """
    connect to database and get data
    format and present result in consloe
    """
    conn = sqlite3.connect("university.db")
    cur = conn.cursor()
    cur.execute("select id, firstname, lastname, exam_score from student;")
    result = cur.fetchall()
    conn.close()
    print("Student Exam Score Report")
    print("=" * 30)
    for row in result:
        fullname = row[1] + " " + row[2]
        print(f"name: {(fullname.upper())} \t score: {row[3]}")

def main():
    """our main program"""
    verify_user()

if __name__ == "__main__":
    main()
